site_name: CrashCatch
site_url: https://keithpotz.github.io/CrashCatch
repo_url: https://github.com/keithpotz/CrashCatch
theme:
  name: material
  palette:
    scheme: slate
    highlightjs: true
    highlightjs_theme: github
    language: en
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.action.edit

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - CMake Integration: cmake.md
  - Examples: examples.md
  - Screenshots: screenshots.md
  - License: license.md
