name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs, theme, and mike
        run: |
          pip install mkdocs mkdocs-material mike

      - name: Set up Git User
        run: | 
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Pull latest gh-pages changes
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages

      - name: Deploy Docs with mike (Versioned)
        run: |
           # Ensure mkdocs.yml is in the correct location
           ls -al # List files in the repository to check mkdocs.yml location
           # Deploy version 1.0.0 docs and set 'latest' as default
           mike deploy 1.0.0 latest --config-file ./mkdocs.yml
           mike set-default latest

      - name: Commit versioned docs to gh-pages
        run: |
          git add -A
          git commit -m "Deploy versioned docs"
          git push origin gh-pages
